<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-9UK4KTH" name="testrunner" tests="13" failures="2" timestamp="2021-08-13T15:38:31 IST" time="644.735" errors="0">
  <testcase name="runScenario" time="52.813" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="68.362" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="73.910" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="29.708" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="48.953" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="45.202" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="33.380" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="59.715" classname="testrunner">
    <failure type="java.lang.AssertionError" message="expected [Thanks for creating alert, we will reach out to you with matching ads] but found []">
      <![CDATA[java.lang.AssertionError: expected [Thanks for creating alert, we will reach out to you with matching ads] but found []
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepdefinition.defect4withoutSIM.it_Should_create_alert(defect4withoutSIM.java:77)
at ✽.it Should create alert(file:///E:/New%20folder/abc/eclipsefiles/quikrtestngg/features/defect.feature:21)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="46.003" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="38.601" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="48.353" classname="testrunner">
    <failure type="java.lang.AssertionError" message="expected [Thanks for creating alert, we will reach out to you with matching ads] but found []">
      <![CDATA[java.lang.AssertionError: expected [Thanks for creating alert, we will reach out to you with matching ads] but found []
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepdefinition.defect3withoutemailid.an_alert_should_be_created(defect3withoutemailid.java:82)
at ✽.an alert should be created(file:///E:/New%20folder/abc/eclipsefiles/quikrtestngg/features/defect.feature:16)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase name="runScenario" time="51.710" classname="testrunner"/>
  <system-out/>
  <testcase name="runScenario" time="48.025" classname="testrunner"/>
  <system-out/>
</testsuite> <!-- testrunner -->
